declare module '@digitalcredentials/did-method-key'
declare module '@digitalbazaar/security-document-loader'
declare module '@interop/did-web-resolver'
declare module '@digitalcredentials/bnid'
declare module 'crypto-ld'
declare module '@digitalcredentials/vc'
declare module '@digitalcredentials/ed25519-signature-2020'
